export const projects = [
  {
    id: 1,
    title: "Weather App",
    description:
      "It's my very first project and understanding of HTML and API",
    image: "src/assets/weather-app.png",
    technologies: ["HTML", "CSS", "React"],
    liveLink: "https://sivalingamr2001.github.io/vite-HTML-deploy/",
  },
  {
    id: 2,
    title: "Hotel Menu Cart Design",
    description: "A simple hotel menu cart design using HTML",
    image: "src/assets/cart.png",
    technologies: ["HTML", "CSS", "React"],
    liveLink: "https://sivalingamr2001.github.io/vite-HTML-cart/",
  },
  {
    id: 3,
    title: "College Landing Page",
    description: "A Modern College Landing Page using HTML",
    image: "src/assets/college.png",
    technologies: ["HTML", "CSS", "React"],
    liveLink: "https://sivalingamr2001.github.io/college-HTML-vite/",
  },
  {
    id: 4,
    title: "Online Tutoring Website",
    description: "Also a simple online tutoring website using HTML",
    image: "src/assets/online.png",
    technologies: ["HTML", "CSS", "React"],
    liveLink: "https://learntolead.netlify.app/",
  },
  {
    id: 5,
    title: "Restaurant Website Design",
    description: "A booking website for a restaurant using HTML",
    image: "src/assets/restaurant.png",
    technologies: ["HTML", "CSS", "React"],
    liveLink: "https://sivalingamr2001.github.io/vite-HTML-trans/",
  },
  {
    id: 6,
    title: "Mini E-commerce Website",
    description: "A Final Project for my HTML Course",
    image: "src/assets/commerce.png",
    technologies: ["HTML", "CSS", "React"],
    liveLink: "https://sivalingamr2001.github.io/E-commerce/",
  },
];
